# @format
# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

clone: # the 'clone' section
    depth: 1 # the depth, in this case the clone will contain last commit

options:
    max-time: 10
    docker: true

pipelines:
    branches:
        master:
            - step:
                  name: Build production
                  image: circleci/node:10.16.0-browsers
                  caches:
                      - node
                  script:
                      - npm install
                      - npm run g_icons
                      - npm run production
                  artifacts:
                      - public_html/**
            - step:
                  name: Deploy to production
                  deployment: production
                  image: samueldebruyn/debian-git
                  script:
                      #   - apt-get update
                      #   - apt-get -qq install git-ftp
                      #   - git config git-ftp.syncroot public_html/
                      #   - git config git-ftp.url $FTP_SERVER
                      #   - git config git-ftp.user $FTP_USERNAME
                      #   - git config git-ftp.password $FTP_PASSWORD
                      #   - git ftp init
                      # after-script:
                      #   - git ftp catchup
                      #   - git ftp push
                      - pipe: atlassian/ftp-deploy:0.2.1
                        variables:
                            USER: $FTP_USERNAME
                            PASSWORD: $FTP_PASSWORD
                            SERVER: $FTP_SERVER
                            REMOTE_PATH: "/"
                            LOCAL_PATH: "public_html/" # Optional
                            # DEBUG: '<boolean>' # Optional
